repos:
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: "./tools/run-mypy"
      language: system
      # trigger for commits changing Python files
      types: [python]
      # use require_serial so that script
      # is only called once per commit
      require_serial: true
      # print the number of files as a sanity-check
      verbose: true
    - id: ruff
      name: ruff
      entry: "./tools/run-ruff"
      language: system
      # trigger for commits changing Python files
      types: [python]
      # use require_serial so that script
      # is only called once per commit
      require_serial: true
      # print the number of files as a sanity-check
      verbose: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: ['--manifest-path', 'experiment/Cargo.toml', '--']
    -   id: cargo-check
        args: ['--manifest-path', 'experiment/Cargo.toml', '--']
    -   id: clippy
        args: ['--manifest-path', 'experiment/Cargo.toml', '--']
