repos:
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: "uv run mypy --strict --ignore-missing-imports"
      language: system
      types: [python]
      require_serial: true
      verbose: true
    - id: ruff
      name: ruff
      entry: "uv run ruff check analysis"
      language: system
      types: [python]
      require_serial: true
      verbose: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: ['--manifest-path', 'experiment/Cargo.toml', '--']
    -   id: cargo-check
        args: ['--manifest-path', 'experiment/Cargo.toml', '--']
    -   id: clippy
        args: ['--manifest-path', 'experiment/Cargo.toml', '--']
